import { StyleSheet } from "react-native";
import { _COL, _H, _WIDTH, FONT, isIOS } from "utils";

const itemDetailsSty = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: _COL.WHITE,
    },
    imageContainer: {
        position: 'absolute',
        top: 0,
        width: _WIDTH,
        overflow: 'hidden',
    },
    imageBackground: {
        width: _WIDTH,
    },
    dotContainer: {
        position: 'absolute',
        bottom: 16,
        flexDirection: 'row',
        alignSelf: 'center',
    },
    dot: {
        width: 8,
        height: 5,
        borderRadius: 3,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        marginHorizontal: 4,
    },
    activeDot: {
        backgroundColor: _COL.WHITE,
        width: 17,
    },
    headerContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
    },
    headerBg: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: _COL.WHITE,
        borderBottomWidth: 1,
        borderBottomColor: _COL.BORDER,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    headerBtn: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: _COL.WHITE,
        padding: 8,
        borderRadius: 24,
        width: 40,
        height: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    headerTitleContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerPlaceholder: {
        width: 40,
        height: 40,
    },
    content: {
        backgroundColor: _COL.WHITE,
        paddingBottom: 140,
    },
    itemContainer: {
        paddingTop: 24,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    animatedTitleContainer: {
        position: 'absolute',
        zIndex: 15,
    },
    animatedTitle: {
        fontSize: 22,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.MAIN_BLACK,
    },
    vegNonVegIcon: {
        marginLeft: 8,
    },
    itemIsStock: {
        fontSize: 12,
        fontFamily: FONT.MEDIUM,
        color: _COL.GREEN,
        lineHeight: 16,
        marginTop: isIOS ? 10 : 5,
    },
    itemIsOutOfStock: {
        fontSize: 12,
        fontFamily: FONT.MEDIUM,
        color: _COL.RED,
        marginTop: 10,
    },
    totalPriceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: _COL.BORDER,
    },
    secondRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    myCartItemTotalPrice: {
        fontFamily: FONT.SEMI_BOLD,
        fontSize: 28,
        color: _COL.FINAL_BLACK,
        lineHeight: isIOS ? undefined : 42,
    },
    myCartItemPrice: {
        fontFamily: FONT.MEDIUM,
        color: _COL.TEXT_GREY_LIGHT,
        fontSize: 12,
        marginLeft: 8,
        lineHeight: isIOS ? undefined : 16,
    },
    quantityContainer: {
        gap: 12,
    },
    myCartItemQuantityMinusBtn: {
        width: 32,
        height: 32,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: _COL.TEXT_GREY,
        backgroundColor: _COL.WHITE,
        alignItems: 'center',
        justifyContent: 'center',
    },
    myCartItemQuantity: {
        fontFamily: FONT.SEMI_BOLD,
        fontSize: 16,
        color: _COL.FINAL_BLACK,
        minWidth: 20,
        textAlign: 'center',
    },
    myCartItemQuantityPlusBtn: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: _COL.SECONDARY_ORANGE,
        alignItems: 'center',
        justifyContent: 'center',
    },
    itemDetailsContainer: {
        marginTop: 5,
    },
    itemDetail: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        borderTopWidth: 1,
        borderTopColor: _COL.BORDER,
        paddingRight: 8,
    },
    itemDetailText: {
        marginLeft: 12,
        fontFamily: FONT.MEDIUM,
        fontSize: 15,
        color: _COL.FINAL_BLACK,
    },
    thirdRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    dotText: {
        fontSize: 24,
        lineHeight: 24,
        color: _COL.TEXT_BLACK,
        marginRight: 8,
    },
    text: {
        color: _COL.MAIN_BLACK,
        fontFamily: FONT.REGULAR,
        fontSize: 14,
        lineHeight: 22,
        marginBottom: 8,
        flex: 1,
    },
    orderForTodayBefore: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.MAIN_BLACK,
        marginTop: 10,
    },
    orderBeforeTime: {
        fontFamily: FONT.SEMI_BOLD,
    },
    isPaidByCompanyBadge: {
        backgroundColor: _COL.SECONDARY_ORANGE,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 42,
        marginLeft: 12,
    },
    isPaidByCompanyText: {
        fontSize: 12,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.WHITE,
    },
    menuContainer: {
        width: _WIDTH * 0.5,
        minHeight: _H * 0.25,
        marginRight: 16,
        borderWidth: 1,
        borderColor: _COL.BORDER_TENTH,
        borderRadius: 12,
        backgroundColor: _COL.THIRD_BG,
        marginBottom: 20,
    },
    menuDotText: {
        fontSize: 24,
        color: _COL.PRIMARY_RED,
        marginRight: 9,
    },
    menuText: {
        color: _COL.MAIN_BLACK,
        fontFamily: FONT.REGULAR,
        fontSize: 14,
        marginTop: 4,
    },
    menuHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderColor: _COL.BORDER_TENTH,
        paddingVertical: 12,
        paddingHorizontal: 12,
    },
    menuItems: {
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 16,
    },
    menuTitle: {
        fontSize: 14,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
    },
    menuTodayText: {
        fontSize: 10,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.PRIMARY_RED,
    },
    noMenuContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    noMenuImage: {
        resizeMode: 'contain',
        marginBottom: 16,
    },
    noMenuText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.LIGHT_PINK,
        lineHeight: 16,
        textAlign: 'center',
    },
    cartItemCountContainer: {
        position: 'absolute',
        height: 16,
        minWidth: 16,
        borderRadius: 20,
        backgroundColor: _COL.SECONDARY_ORANGE,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
        top: -2,
        right: -4,
    },
    cartItemCountText: {
        fontSize: 10,
        fontFamily: FONT.MEDIUM,
        color: _COL.WHITE,
    },
});

export default itemDetailsSty;
