import { StyleSheet } from "react-native";
import { _COL, _WIDTH, FONT } from "utils";

const orderSummarySty = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: _COL.WHITE,
    },
    divider: {
        height: 1,
        backgroundColor: _COL.BORDER_FOURTH,
        marginTop: 16,
    },
    backBtn: {
        position: 'absolute',
        left: 16,
        zIndex: 1,
        bottom: -2,
    },
    title: {
        fontSize: 20,
        width: '100%',
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
        textAlign: 'center',
        lineHeight: 24
    },
    orderItemsContainer: {
        marginVertical: 16,
        marginHorizontal: 16,
    },
    orderItemsContentContainer: {
        paddingBottom: 20,
        paddingTop: 16,
        gap: 20,
        borderBottomWidth: 2,
        borderColor: _COL.BORDER,
        borderStyle: 'dashed',
    },
    ordersHeading: {
        fontSize: 18,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
    },
    totalAmountContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: _COL.BORDER,
    },
    totalAmountText: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.FINAL_BLACK,
    },
    totalAmountValue: {
        fontSize: 14,
        fontFamily: FONT.BOLD,
        color: _COL.FINAL_BLACK,
    },
    outletAddressContainer: {
        marginTop: 16,
        marginHorizontal: 16,
        borderBottomColor: _COL.BORDER,
        borderBottomWidth: 1,
        paddingBottom: 16,
    },
    outletAddressText: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.TEXT_GREY,
        marginTop: 8,
    },
    billInfoContainer: {
        marginTop: 16,
        paddingHorizontal: 16,
        paddingBottom: 20,
    },
    billInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    billRowContainer: {
        marginVertical: 12,
        gap: 8,
    },
    billInfoText: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.MAIN_BLACK,
    },
    billInfoAmount: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.FINAL_BLACK,
    },
    couponCodeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 14,
        borderRadius: 8,
        marginTop: 4,
        backgroundColor: _COL.SECONDARY_ORANGE_10,
    },
    couponCodeText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.FINAL_BLACK,
        marginLeft: 12,
        alignSelf: 'center',
    },
    applyText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.FINAL_BLACK,
        textDecorationLine: 'underline',
        textDecorationStyle: 'solid',
        textShadowOffset: { width: 0, height: 0 },
    },
    billInfoTotalAmountContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
    },
    billInfoTotalAmountText: {
        fontSize: 14,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
    },
    walletBalanceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 19,
        borderBottomWidth: 1,
        borderTopWidth: 1,
        borderColor: _COL.BORDER,
        paddingVertical: 12,
    },
    walletBalanceText: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.MAIN_BLACK,
    },
    walletBalanceAmount: {
        fontSize: 12,
        fontFamily: FONT.REGULAR,
        color: _COL.FINAL_BLACK,
        marginTop: 4,
    },
    payAmountContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
    },
    payAmountText: {
        fontSize: 16,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
    },
    payAmountValue: {
        fontSize: 16,
        fontFamily: FONT.BOLD,
        color: _COL.FINAL_BLACK,
    },
    cancelText: {
        color: _COL.FINAL_BLACK,
        fontSize: 14,
        fontFamily: FONT.SEMI_BOLD,
        textAlign: 'center',
        textDecorationLine: 'underline',
        textDecorationStyle: 'solid',
    },
    addBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: _COL.BLACK,
        borderRadius: 14,
        backgroundColor: _COL.WHITE,
    },
    addText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.FINAL_BLACK,
        lineHeight: 16,
    },
    deleteSVG: {
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 7,
    },
    codeDiscount: {
        fontSize: 14,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.SECONDARY_GREEN,
        alignSelf: 'center',
    },
    schdulePickupContainer: {
        flexDirection: 'row',
        backgroundColor: _COL.TRACK_ONE,
        borderRadius: 66,
    },
    schedulePickupOptionNow: {
        paddingVertical: 10,
        width: _WIDTH / 2.2,
        color: _COL.FINAL_BLACK,
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
    },
    schedulePickupOptionLater: {
        paddingVertical: 10,
        width: _WIDTH / 2.2,
        color: _COL.FINAL_BLACK,
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
    },
    schedulePickupNow: {
        fontSize: 16,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
        textAlign: 'center',
    },
    schedulePickupLater: {
        fontSize: 16,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
        textAlign: 'center',
    },
    schedulePickupOption: {
        borderColor: _COL.PRIMARY_RED,
        borderRadius: 66,
        borderWidth: 1,
        backgroundColor: _COL.WHITE,
    },
    schedulePickupOptionText: {
        color: _COL.PRIMARY_RED,
    },
    pickUpOrderDetail: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderRadius: 10,
        marginTop: 16,
        backgroundColor: _COL.SECONDARY_ORANGE_10,
    },
    pickUpOrderDetailText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.MAIN_BLACK,
        marginLeft: 12,
    },
    selectedDaysContainer: {
        paddingVertical: 11,
        paddingHorizontal: 18,
        borderRadius: 48,
        backgroundColor: _COL.FORTH_BG,
        marginTop: 10,
    },
    selectedDaysText: {
        fontSize: 12,
        fontFamily: FONT.MEDIUM,
        color: _COL.MAIN_BLACK,
        lineHeight: 20,
    },
    lunchTimeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginTop: 12,
    },
    lunchTimeText: {
        fontSize: 12,
        fontFamily: FONT.MEDIUM,
        color: _COL.TEXT_GREY_LIGHT,
        marginLeft: 6,
    },
    mealScheduleText: {
        fontSize: 18,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
        marginTop: 16,
        marginBottom: 22
    },
    mealScheduleItemContainer: {
        marginBottom: 14,
        borderBottomWidth: 1,
        borderColor: _COL.BORDER,
        paddingBottom: 14,
    },
    mealScheduleItemDay: {
        fontSize: 14,
        fontFamily: FONT.REGULAR,
        color: _COL.FINAL_BLACK,
    },
    mealScheduleItemPrice: {
        fontSize: 14,
        fontFamily: FONT.SEMI_BOLD,
        color: _COL.FINAL_BLACK,
    },
    mealScheduleItems: {
        fontSize: 12,
        fontFamily: FONT.REGULAR,
        color: _COL.TEXT_GREY,
        marginTop: 8,
        textAlign: 'left',
        width: _WIDTH - 100,
    },
    vegNonVegIcon: {
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    addMoreItemsText: {
        fontSize: 14,
        fontFamily: FONT.MEDIUM,
        color: _COL.TEXT_GREY,
        lineHeight: 24,
    },
    dropdownContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: 15,
        paddingRight: 13,
        marginTop: 9,
        borderWidth: 1.5,
        borderColor: _COL.BORDER,
        borderRadius: 12,
        paddingVertical: 12,
        backgroundColor: _COL.WHITE,
    },
    dropdownSelectedText: {
        fontSize: 14,
        color: _COL.FINAL_BLACK,
        fontFamily: FONT.REGULAR,
    },
    dropdownPlaceholderText: {
        fontSize: 14,
        color: _COL.TEXT_GREY_LIGHT,
        fontFamily: FONT.REGULAR,
    },
    dropdownListContainer: {
        backgroundColor: _COL.WHITE,
        borderWidth: 1.5,
        borderColor: _COL.BORDER,
        borderRadius: 12,
        marginTop: 4,
        position: 'absolute',
        top: 55,
        left: 0,
        right: 0,
        zIndex: 100,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        overflow: 'hidden',
    },
    dropdownItemText: {
        padding: 12,
        fontSize: 14,
        color: _COL.FINAL_BLACK,
        fontFamily: FONT.REGULAR,
        borderBottomWidth: 1,
        borderBottomColor: _COL.BORDER,
    }
});

export default orderSummarySty;
